name: Publish Docker image

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
      - name: Check if branch was created by dependabot
        id: dependabot_check
        run: |
          ref_branch=${{ github.ref_name }}
          if [[ $ref_branch =~ ^dependabot/ ]]; then
            echo "continue=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Check out the repo
        # if: steps.dependabot_check.outputs.continue == 'true'
        # uses: actions/checkout@v4
        run: echo "Debug ${{ steps.dependabot_check.outputs.continue }}"

      - name: Log in to Docker Hub
        if: steps.dependabot_check.outputs.continue == 'true'
        uses: docker/login-action@0d4c9c5ea7693da7b068278f7b52bda2a190a446
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        if: steps.dependabot_check.outputs.continue == 'true'
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81
        with:
          images: nojussta/restoresa-backend-t
          tags: v1.${{ github.run_number}}

      - name: Build and push Docker image
        if: steps.dependabot_check.outputs.continue == 'true'
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0
        env:
          STRIPE_TOKEN: ${{ secrets.STRIPE_TOKEN }}
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
